<img src="https://raw.githubusercontent.com/paular143/images_notebooks/master/logo-sin-nombre.png" alt="Universidad de Los Andes" style="width: 90px;" align="left" frameborder="300"/>

**UNIVERSIDAD DE LOS ANDES** <br>
**FACULTAD DE ECONOMÍA - EDUCACIÓN CONTINUADA** <br>
**Análisis espacial de datos y sus aplicaciones en Python** <br>
**PROFESORES:** Germán González <br><br>


# Clase 8: Clasificadores

In [1]:
# !pip3 install numpy 
# !pip3 install pandas 
# !pip3 install seaborn 
# !pip3 install sklearn 

import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn import metrics
import itertools


def graficar_matriz_confusion(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('')
    plt.xlabel('')

/Users/germangonzalez/.pyenv/versions/3.7.5/envs/motus/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

## Cargar datos

In [2]:
Datos_clima = pd.read_excel('Clima.xlsx')

In [3]:
Datos_clima

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.503167,16.9,21.8,0,0
1,2008-12-02,Albury,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,4.437189,4.503167,17.2,24.3,0,0
2,2008-12-03,Albury,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,4.437189,2.000000,21.0,23.2,0,0
3,2008-12-04,Albury,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,4.437189,4.503167,18.1,26.5,0,0
4,2008-12-05,Albury,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.000000,17.8,29.7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,4.437189,4.503167,9.4,20.9,0,0
142189,2017-06-21,Uluru,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,4.437189,4.503167,10.1,22.4,0,0
142190,2017-06-22,Uluru,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,4.437189,4.503167,10.9,24.5,0,0
142191,2017-06-23,Uluru,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,4.437189,4.503167,12.5,26.1,0,0
142192,2017-06-24,Uluru,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,1016.5,3.000000,2.000000,15.1,26.0,0,0

## Crear dummies espaciales

In [4]:
Datos_clima =  pd.get_dummies(Datos_clima, prefix=['Location'], columns=['Location'])

In [5]:
Datos_clima

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,Location_Townsville,Location_Tuggeranong,Location_Uluru,Location_WaggaWagga,Location_Walpole,Location_Watsonia,Location_Williamtown,Location_Witchcliffe,Location_Wollongong,Location_Woomera
0,2008-12-01,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,...,0,0,0,0,0,0,0,0,0,0
1,2008-12-02,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,...,0,0,0,0,0,0,0,0,0,0
2,2008-12-03,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,...,0,0,0,0,0,0,0,0,0,0
3,2008-12-04,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,...,0,0,0,0,0,0,0,0,0,0
4,2008-12-05,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,...,0,0,1,0,0,0,0,0,0,0
142189,2017-06-21,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,...,0,0,1,0,0,0,0,0,0,0
142190,2017-06-22,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,...,0,0,1,0,0,0,0,0,0,0
142191,2017-06-23,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,...,0,0,1,0,0,0,0,0,0,0
142192,2017-06-24,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,...,0,0,1,0,0,0,0,0,0,0

## Separar variable dependiente e independientes

In [6]:
y = np.array(Datos_clima['RainTomorrow'])
#### --- Quitamos la variable dependiente y los datos de localizacion --- #### 
x_data = Datos_clima.drop(['RainTomorrow','Date'], axis=1)
x_data.head()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,...,Location_Townsville,Location_Tuggeranong,Location_Uluru,Location_WaggaWagga,Location_Walpole,Location_Watsonia,Location_Williamtown,Location_Witchcliffe,Location_Wollongong,Location_Woomera
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,...,0,0,0,0,0,0,0,0,0,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,...,0,0,0,0,0,0,0,0,0,0
2,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,...,0,0,0,0,0,0,0,0,0,0
3,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,...,0,0,0,0,0,0,0,0,0,0
4,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,...,0,0,0,0,0,0,0,0,0,0

## Normalización de los Datos

In [7]:
x = (x_data - np.mean(x_data)) / np.std(x_data)

In [8]:
x.head()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,...,Location_Townsville,Location_Tuggeranong,Location_Uluru,Location_WaggaWagga,Location_Walpole,Location_Watsonia,Location_Williamtown,Location_Witchcliffe,Location_Wollongong,Location_Woomera
0,0.189954,-0.045964,-0.207757,0.305648,0.677661,0.614850,0.113891,-1.435935,-1.475456,-1.220966,...,-0.147631,-0.146759,-0.103983,-0.146208,-0.142219,-0.146784,-0.135214,-0.145604,-0.146383,-0.146559
1,-0.749174,0.263480,-0.278989,0.305648,-1.130034,0.385532,-1.312265,-1.289821,-1.045586,-1.116203,...,-0.147631,-0.146759,-0.103983,-0.146208,-0.142219,-0.146784,-0.135214,-0.145604,-0.146383,-0.146559
2,0.111694,0.347873,-0.278989,0.457874,0.564680,0.844167,-1.629188,-1.046299,-1.490279,-0.981508,...,-0.147631,-0.146759,-0.103983,-0.146208,-0.142219,-0.146784,-0.135214,-0.145604,-0.146383,-0.146559
3,-0.467436,0.671383,-0.278989,-1.216614,-0.339167,-1.105034,-1.259444,-1.728162,-0.007969,-0.367897,...,-0.147631,-0.146759,-0.103983,-0.146208,-0.142219,-0.146784,-0.135214,-0.145604,-0.146383,-0.146559
4,0.831692,1.276205,-0.160269,0.077309,-0.791091,0.156214,0.694918,-0.900186,-1.015940,-1.385593,...,-0.147631,-0.146759,-0.103983,-0.146208,-0.142219,-0.146784,-0.135214,-0.145604,-0.146383,-0.146559

In [9]:
## ---- Definir clase --- # 
scaler = StandardScaler()
## ---- Ajustar datos --- ### 
print(scaler.fit(x_data))

StandardScaler()

In [10]:
## --- Estimar transformación --- ## 
x = scaler.transform(x_data)

In [11]:
x

array([[ 0.18995446, -0.04596425, -0.20775676, ..., -0.14560444,
        -0.14638326, -0.1465586 ],
       [-0.74917416,  0.26347957, -0.2789887 , ..., -0.14560444,
        -0.14638326, -0.1465586 ],
       [ 0.11169374,  0.34787335, -0.2789887 , ..., -0.14560444,
        -0.14638326, -0.1465586 ],
       ...,
       [-1.34395563,  0.29161083, -0.2789887 , ..., -0.14560444,
        -0.14638326, -0.1465586 ],
       [-1.06221704,  0.51666089, -0.2789887 , ..., -0.14560444,
        -0.14638326, -0.1465586 ],
       [-0.68656559,  0.53072651, -0.2789887 , ..., -0.14560444,
        -0.14638326, -0.1465586 ]])

In [12]:
## --- Devolver --- ###
scaler.inverse_transform(x)

array([[13.4, 22.9,  0.6, ...,  0. ,  0. ,  0. ],
       [ 7.4, 25.1,  0. , ...,  0. ,  0. ,  0. ],
       [12.9, 25.7,  0. , ...,  0. ,  0. ,  0. ],
       ...,
       [ 3.6, 25.3,  0. , ...,  0. ,  0. ,  0. ],
       [ 5.4, 26.9,  0. , ...,  0. ,  0. ,  0. ],
       [ 7.8, 27. ,  0. , ...,  0. ,  0. ,  0. ]])

## Crear muestra de entrenamiento y de prueba

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=75)

print('x entrenamiento dimension', x_train.shape)
print('y entrenamiento dimension: ', y_train.shape)
print('x prueba dimension: ', x_test.shape)
print('y prueba dimension: ', y_test.shape)

x entrenamiento dimension (113754, 64)
y entrenamiento dimension:  (113754,)
x prueba dimension:  (28439, 64)
y prueba dimension:  (28439,)

# Modelos de clasificación

## Logit

In [14]:
Logit = LogisticRegression(max_iter=1000)

### --- Ajustar a los datos de entrenamiento --- ### 
Logit.fit(x_train, y_train)

# Calcular la precisión utilizando nuestro modelo entrenado y datos de prueba:
print('Precisión: {}'.format(Logit.score(x_test, y_test)))

Precisión: 0.8450367453145329

## Logit Optimizado

In [ ]:
### 
fold = KFold(n_splits=10, shuffle=True, random_state=777)
### --- Grilla de parametros a optimizar --- ### 
grid = {'C': np.power(10.0, np.arange(-10, 10)), 'solver': ['newton-cg']}

### --- Parametros generales --- ### 
clf = LogisticRegression(penalty='l2', random_state=777, max_iter=10000, tol=20)

### --- Optimizacion de parametros --- ### 
Logit_optimizado = GridSearchCV(clf, grid, scoring='roc_auc', cv=fold)

### --- Ajustar a los datos de entrenamiento --- ### 
Logit_optimizado.fit(x_train, y_train)
### --- Resultados --- ### 
print('Precisión:', Logit_optimizado.best_score_)

In [ ]:
Logit_optimizado.best_estimator_

In [ ]:
GridSearchCV

## Maquina de Soporte Vectorial

In [ ]:
################# -------------- Bagging SVM ---------- #################
n_estimators = 100
SVM = BaggingClassifier(SVC(C=1, kernel='linear', probability = True,verbose=10), max_samples=1.0 / n_estimators, n_estimators=n_estimators)
SVM.fit(x_train, y_train)
SVM.score(x_test, y_test)

## Random Forest

In [ ]:
################# -------------- Random Forest ---------- #################
RandomForest = RandomForestClassifier(n_estimators = 50, random_state = 42)
RandomForest.fit(x_train, y_train)
RandomForest.score(x_test, y_test)

In [ ]:
x_test

In [ ]:
Resultados

## Matriz de confusión

## Logit

In [ ]:
################# -------------- Logit ---------- #################
Probabilidades = Logit.predict_proba(x_test)
Resultados = Probabilidades[:,1] 
prob = 0.4
Resultados[Resultados >=prob,] = 1
Resultados[Resultados < prob,] = 0
cnf_matrix = metrics.confusion_matrix(y_test,pd.DataFrame(Resultados))
plt.figure()
graficar_matriz_confusion(cnf_matrix, classes=['Negativo','Positivo'],title='Logit')

## SVM

In [ ]:
################# -------------- SVM ---------- #################
Probabilidades = SVM.predict_proba(x_test)
Resultados = Probabilidades[:,1] 
prob = 0.5
Resultados[Resultados >=prob,] = 1
Resultados[Resultados < prob,] = 0
cnf_matrix = metrics.confusion_matrix(y_test,pd.DataFrame(Resultados))
plt.figure()
graficar_matriz_confusion(cnf_matrix, classes=['Negativo','Positivo'],title='SVM')

In [ ]:
################# -------------- Random Forest ---------- #################
Probabilidades = RandomForest.predict_proba(x_test)
Resultados = Probabilidades[:,1] 
prob = 0.4
Resultados[Resultados >=prob,] = 1
Resultados[Resultados < prob,] = 0
cnf_matrix = metrics.confusion_matrix(y_test,pd.DataFrame(Resultados))
plt.figure()
graficar_matriz_confusion(cnf_matrix, classes=['Negativo','Positivo'],title='Random Forest')

## Métricas de evaluación

In [ ]:
####### -------- Predict test -------- ######
####### -------- Logit -------- ######
yhat_Logit = Logit_optimizado.predict_proba(x_test)

####### -------- SVM -------- ######
yhat_Svm = SVM .predict_proba(x_test)

####### -------- Random Forest -------- ######
yhat_Random = RandomForest.predict_proba(x_test)

In [ ]:
####### -------- Logit -------- ######
fpr_logit, tpr_logit, threshold = metrics.roc_curve(y_test, yhat_Logit[:,1])
roc_auc_logit = metrics.auc(fpr_logit, tpr_logit)
####### -------- SVM -------- ######
fpr_svm, tpr_svm, threshold = metrics.roc_curve(y_test, yhat_Svm[:,1])
roc_auc_svm = metrics.auc(fpr_svm, tpr_svm)
####### -------- Random Forest -------- ######
fpr_random, tpr_random, threshold = metrics.roc_curve(y_test, yhat_Random[:,1])
roc_auc_random = metrics.auc(fpr_random, tpr_random)

In [ ]:
####### ------------------ Metrics ------------------------ ######
plt.figure(figsize=(8,7))
plt.plot(fpr_logit, tpr_logit, label='Logit (area = %0.3f)' % roc_auc_logit, linewidth=2)
plt.plot(fpr_svm, tpr_svm, label='SVM (area = %0.3f)' % roc_auc_svm, linewidth=2)
plt.plot(fpr_random, tpr_random, label='Random Forest (area = %0.3f)' % roc_auc_random, linewidth=2)

plt.plot([0, 1], [0, 1], 'k--', linewidth=2)
plt.xlim([-0.05, 1.0])
plt.ylim([-0.05, 1.05])
plt.xlabel('Tasa falsos positivos', fontsize=18)
plt.ylabel('Tasa verdaderos positivos', fontsize=18)
plt.title('ROC', fontsize=18)
plt.legend(loc="lower right")
plt.show()